fix yaml

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -18,15 +18,15 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install tidy -y
-        tidy -e index.html || true  # This lints the HTML; won't fail the build
+        tidy -e index.html || true  # Lint HTML, will not fail the build
 
     - name: Archive Website Files
       run: |
-        mkdir artifact
-        cp -r * artifact
+        mkdir ../artifact
+        cp -r * ../artifact
 
     - name: Upload Artifacts
       uses: actions/upload-artifact@v4
       with:
         name: portfolio-web
-        path: artifact
+        path: ../artifact
